### ISSUE TITLE
Questions about Tork Architecture

### ISSUE THREAD

**Issue by gaby** [runabol/tork#172]
@runabol I had a few questions after looking at the docker-compose.yml from here https://github.com/runabol/tork/blob/main/docker-compose.yaml

- Does the database need be exposed to the whole network?
- Which services need to access the DB? Looking at the docs it should only be the coordinator which i'm assuming is part of this repo
- Why use swagger-ui instead of serving swagger directly using an `Echo` middleware?
- What's the purpose between Tork and Tork-Web? Is the UI just a frontend with no backend?
- RabbitMQ is known to be a resource hog, have you considered using Queues/Lists with Redis? Their Golang support is excellent
- What's the purpose of the "migration" cmd?
- The front end is using `BACKEND_URL: http://host.docker.internal:8000` but there are no services running on port 8000, is that assuming that the user ran `/tork` outside of Docker?

Trying to get a general understanding of the architecture before doing another PR :-)

Source: https://www.tork.run/architecture

**Comment by runabol** [comment]
@gaby  Great questions!

The `docker-compose.yaml` is meant for development and quick-and-dirty experimentation with Tork. I should probably clarify this somewhere in the docs. 

> Does the database need be exposed to the whole network?

Nope. `localhost` should be enough.

> Which services need to access the DB? Looking at the docs it should only be the coordinator which i'm assuming is part of this repo

Correct. Only the Coordinator (`./tork run coordinator` or `./tork run standalone`) . The workers are designed to be completely stateless. 

> Why use swagger-ui instead of serving swagger directly using an Echo middleware?

[We tried that](https://github.com/runabol/tork/pull/139#issuecomment-1714561407). But the Swagger deps really bloat the build.

> What's the purpose between Tork and Tork-Web? Is the UI just a frontend with no backend?

Correct. I wanted to have a clean separation of of backend and UI. Since it's a general-purpose workflow engine it stands to reason that many UIs can be applied to it for custom use cases. Example: https://github.com/runabol/code-execution-demo

> RabbitMQ is known to be a resource hog, have you considered using Queues/Lists with Redis? Their Golang support is excellent

Tork has a [Broker](https://github.com/runabol/tork/blob/115dd562710dd4079011df368b36af7e35649c7b/mq/broker.go#L18C6-L18C6)  abstraction so it's relatively easy to [plug-in](https://www.tork.run/broker) additional broker implementations (e.g. Redis). I picked RabbitMQ because it supports [acks](https://www.rabbitmq.com/confirms.html) out of the box which means that if a worker node crashes mid-procssing, the task will automatically get re-queued and handled by another worker. The same can probably be achieved with Redis but I don't believe it comes "for free". 

> What's the purpose of the "migration" cmd?

Initializing the Postgres DB. This process could probably use some love. I took a quick look at this [migate](https://github.com/golang-migrate/migrate) tool but haven't spent too much time on it.

> The front end is using BACKEND_URL: http://host.docker.internal:8000 but there are no services running on port 8000, is that assuming that the user ran /tork outside of Docker?

That's correct. Tork generally runs directly on the host because it interacts with the Docker daemon to execute tasks in containers. That being said, the Coordinator does not (unless Tork is running in `standalone` mode) interact with the Docker daemon, only workers do, so it might be worth documenting how to run a Coordinator in Docker.

**Comment by gaby** [comment]
@runabol Thanks! That answers a lot of my questions!

Some thoughts I had:
- Provide a TorkSdocker image, with just the bare-minimum.
- Provide a Full Tork image that has the Web-Ui, and the Tork binary.
  - The easier it's to start and run, the better. Right now it requires 5-6 containters to run Tork.
  - Tork worker can mount `-v /var/run/docker.sock` and get access to the Host dockerd
- Add documentation about how to run a Tork worker, I haven't seen any.
  - On that, does the worker only recieves jobs and sends back results? Does it need constant connection to the coordinator, or it relies on the broker for tasking?
- I really wish Swagger was bundle, maybe that is something the Full Tork Image can do, anyone using Tork is going to want access to Swagger, so may as well make it easy for the user. It can be a config option to enable/disable the interface.
  - If the above becomes a thing, the Swagger JSON can/should be generated with the CI
- The migrate command should be integrated into Tork start-up. The engine should check if it needs to migrate or not, based on a DB existing.

**Comment by runabol** [comment]
@gaby I really like your idea. Yes, maybe we can have a few docker image flavors: `tork-standalone` for a Coordinator + Worker + Swagger + Web UI, `tork-coordinator` for Coordinator + Swagger, and `tork-worker`.

It should be fairly easy to have nginx or something on the image to reverse proxy `/swagger/*` requests to the swagger UI process and everything else to Tork. 

We would have to test the socket mount on Linux, Mac and Windows but I think that should work. 

For configs people could use env vars. That's already supported. or maybe mount a directory on the host and use TORK_CONFIG env var to tell Tork where is their config.toml

I can also put my docker hub creds in the repo's secrets so we can push it there like I do on tork-web: https://github.com/runabol/tork-web/blob/main/.github/workflows/docker.yml

Thoughs?

**Comment by runabol** [comment]
The worker and coordinator never talk directly to each other. Only through broker to reduce downtime in case of deployments and for task queuing purposes in case either is busy.

**Comment by runabol** [comment]
Agreed on the DB migration. I would add maybe have a flat to "opt in" for the migration in case the change to the DB could be catastrophic to their data.

**Comment by gaby** [comment]
Yeah, that makes sense (images). If the UI doesnt support TLS, then it makes sense to have NGINX in the mix. 

You can use Docker Hub and/or GitHub Container Registry (ghcr.io) which doesnt require any special creds.

**Comment by gaby** [comment]
Normally even though I dont use Docker Hub all the time, I still create the project there so people don't squat on the name 😂

**Comment by runabol** [comment]
> Yeah, that makes sense (images). If the UI doesnt support TLS, then it makes sense to have NGINX in the mix.
> 
> You can use Docker Hub and/or GitHub Container Registry (ghcr.io) which doesnt require any special creds.

The NGINX thing is not so much for TLS but because you have two servers listening on two different ports: Tork and The Swagger UI. So NGINX sits in front of both so the user doesn't have to use two ports.

**Comment by runabol** [comment]
I'm totally cool with using whatever docker registry.

**Comment by gaby** [comment]
> > Yeah, that makes sense (images). If the UI doesnt support TLS, then it makes sense to have NGINX in the mix.
> > You can use Docker Hub and/or GitHub Container Registry (ghcr.io) which doesnt require any special creds.
> 
> The NGINX thing is not so much for TLS but because you have two servers listening on two different ports: Tork and The Swagger UI. So NGINX sits in front of both so the user doesn't have to use two ports and it feels like it's all one server.

Ahhh, that's true.

**Comment by runabol** [comment]
Also avoids CORS issues

**Comment by gaby** [comment]
@runabol One last question, have you considered adding a mode where the Worker can run commands on the host it's running on? Instead of having to use a Docker Image?

I can see the use case for stuff like doing backups, or moving data, etc

**Comment by runabol** [comment]
@gaby I did. In fact this was the default mode in a [previous iteration] I built. 

The two main problems are that you lose the ability to enforce limits (CPU/RAM) on the execution and you depend on having certain tools installed on the host. 

If it's really desirable we could probably extends the support Tork has for `volumes`: https://www.tork.run/rest#submit-a-job to let the user mount a volume on the host and then they can use a [special queue](https://www.tork.run/installation#queues) to route to that particular host.

**Comment by gaby** [comment]
> @gaby I did. In fact this was the default mode in a [previous iteration](https://github.com/runabol/piper) of a workflow engine I built.
> 
> The two main problems are that you lose the ability to enforce limits (CPU/RAM) on the execution of the task and you depend on having certain tools installed on the host. It's also a good bit less secure.
> 
> If it's really desirable we could probably extend the support Tork has for [volumes](https://www.tork.run/rest#submit-a-job) to let the user mount a volume on the host and then they can use a [special queue](https://www.tork.run/installation#queues) to route to that particular host.

I like it, using volumes and for example `ubuntu:latest` should be enough to do tasks like those.

Can special queues be created through the API?

**Comment by runabol** [comment]
> Can special queues be created through the API?

It's actually done through the worker [configuration](https://www.tork.run/installation#queues):

```yaml
# config.toml
[worker.queues]
default = 5
backups = 1
otherqueue = 1
video = 1
# etc
```
When a worker boots up it registers for the queues it wants to process work from.

(this goes back to your excellent point of missing documentation for Worker start up. I'll add that.)

**Comment by runabol** [comment]
We may want to make the "mount an arbitrary directory" from the host an opt-in feature in case the Tork administrator does not want to allow it for security reasons.

**Comment by gaby** [comment]
> We may want to make the "mount an arbitrary directory" from the host an opt-in feature in case the Tork administrator does not want to allow it for security reasons. And also maybe have an "allowlist" for which directories are allowed even if mounting is allowed.

100% Agree, #SecurityFirst

**Comment by gaby** [comment]
> > Can special queues be created through the API?
> 
> @gaby It's actually done through the worker [configuration](https://www.tork.run/installation#queues):
> 
> ```yaml
> # config.toml
> [worker.queues]
> default = 5
> backups = 1
> otherqueue = 1
> video = 1
> # etc
> ```
> 
> When a worker boots up it registers for the queues it wants to process work from.
> 
> (this goes back to your excellent point of missing documentation for Worker start up. I'll add that.)
> 
> by the way, the number next to each queue specifies how many tasks from that particular queue can a worker handle concurrently.

That's very cool! Thanks for the info
