### ISSUE TITLE
[Question] Workflow with arbitrary input

### ISSUE THREAD

**Issue by v36372** [runabol/tork#190]
I am building a job system that accepts user input. Some of the [examples](https://github.com/runabol/tork/blob/main/examples) accept an `input` section, but they are all concrete values. It would be better if we can substitute values in. Or maybe I am missing something in the docs?

Another related point is secret management. Having secrets in plain text in job yaml is frown upon for production use, is there a better way to handle secrets?

**Comment by runabol** [comment]
@v36372 For inputs, I would suggest using some sort of templating language to templatize your job's YAML and then replace the values in the `inputs` section and then sending the rendered result to the Tork API. If you're using Go to build your job system, this should be easy to accomplish using [text/template](https://pkg.go.dev/text/template) for example. 

As for secrets, this is not well-documented, but there is a redact middleware that can be turned on via [configuration](https://www.tork.run/config):

```toml
[middleware.job.redact]
enabled = false
```
or using an environment variable:

```shell
TORK_MIDDLEWARE_JOB_REDACT_ENABLED=true
```

What this will do is automatically redact and value in the `job.inputs` and `task.env` sections that contains the keywords `SECRET`, `PASSWORD` and `ACCESS_KEY` (not case-sensitive) in their names on any API responses that returns jobs or tasks. 

I hope this help.

**Comment by v36372** [comment]
Nice, I could use that redact middleware.

I just found out that the [Extend](https://www.tork.run/customize) section and the [demo](https://github.com/runabol/code-execution-demo) could be what I need for arbitrary input.

I shouldve created a separated issue but another unrelated question: From what I gouge from docs and code, cron schedule is not supported yet. Do you think it's should be included in the job API or job yaml? Something like this could work:
```go
	input := &input.Job{
		Name:        "code execution",
		Tasks:       []input.Task{task},
		ScheduledAt: time.Now().Add(24 * time.Hour),
	}

	job, err := engine.SubmitJob(c.Request().Context(), input, listener)

```


```yaml
name: hello world
output: "{{ tasks.hello }}"
cron: * * * * *
tasks:
  - var: hello
    name: simple task
    image: ubuntu:mantic
    run: echo -n hello world > $TORK_OUTPUT
```

**Comment by runabol** [comment]
Yea, that's a good point. If you'd like to build your job system directly on Tork you can definitely expose custom endpoints to have more fine-grained control over inputs. 

As for job scheduling, you're right, this isn't supported yet. It's something I'm planning on taking a look at in the not too far future. Meanwhile, you could potentially use cron itself to trigger jobs through the Tork API.
