### ISSUE TITLE
Feedback wanted

### ISSUE THREAD

**Issue by runabol** [runabol/tork#202]
I would love to get some feedback on how easy it is to get started with Tork when following the [docs](https://www.tork.run). 

In particular: 

1. Going through the [Quick Start](https://www.tork.run/#quick-start).
2. [Installation](https://www.tork.run/installation)
3. Submitting jobs.
4. [Extending](https://www.tork.run/customize) Tork.
5. Anything else you think is interesting.

**Comment by c-nv-s** [comment]
just curious as to why you chose rabbitmq?

**Comment by v36372** [comment]
When extending tork, I bumped into some issues:
- a working docker-compose that support both 2 cases:
  - a standalone dind container
  - a container that run dockerd and my code (the reason for this is I have some code/dependencies on the host machine that  I want to mount to the worker container. Couldnt do that when dind is the host)
- The validation rules for mount types are not clear. `source/target is not empty` is not very helpful. And the regex for mount path currently not accept paths that includes `.`
- This is more like a feature request and I mentioned it in #190 already. Ability to specify schedule for job would nice. Something like this:
```go
	input := &input.Job{
		Name:        "code execution",
		Tasks:       []input.Task{task},
		ScheduledAt: time.Now().Add(24 * time.Hour),
	}
```

**Comment by runabol** [comment]
Thanks for your feedback!

Some thoughts:

1. Docker-In-Docker isn't really something I would generally recommend for a production setup. There's a rather [famous post](http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/) by the creator of DIND that has all the details if you're interested. One of the reasons I picked Go for Tork is precisely because it can run as a self-contained binary without any runtimes, interpreters, VMs and other complexities. I don't see the advantage of wrapping the binary in a container and then having to your hack your way into the Docker daemon in order to run tasks. 

2. Agreed that the validation rules can be a lot more friendly. How do you feel about submitting a PR? That would be awesome. If you're interested, this is where all input validation occurs: https://github.com/runabol/tork/blob/main/input/validate.go

3. There's no support for scheduling job yet, but it did come up a few times and probably worth adding to the roadmap.

4.  Running `standalone` means you can not scale out. Everything runs on a single machine. That could be fine for many use cases where the workload is relatively small. But if you have a setup where you need to run thousands of jobs in parallel then running distributed becomes very appealing. Similarly, when you run distributed you can't use `inmem` broker because the broker state is limited to one host. You'll need a persistent broker (e.g. RabbitMQ) to allow you to send messages between different hosts.

6. A good bit more battle testing. I'm about to use it myself for a pretty major project. And I'm hoping others will do as well for their projects. @ppcololo has been providing a lot of great feedback that is helping me harden Tork for production use. But more time is needed to really declare it "production-ready".

**Comment by ppcololo** [comment]
For me it was really cool expirience. 
I reached my goals: you provided `shell runtime` and after that I prepared `tork-docker` image and deployed it to K8s via helm chart and could scale it really easy from 1 to 100x workers. (one thing I didn't get - is `output` in the `task` - maybe you have to store all `tork-worker output` in the database without adding `$TORK_OUTPUT`)
And thanks a lot that you are fixing all bugs really fast.
Now there are some `feature request` created from my side but they are about `tork-web` - you have to improve the `face` of your app :)

**Comment by v36372** [comment]
> For me it was really cool expirience. I reached my goals: you provided `shell runtime` and after that I prepared `tork-docker` image and deployed it to K8s via helm chart and could scale it really easy from 1 to 100x workers. (one thing I didn't get - is `output` in the `task` - maybe you have to store all `tork-worker output` in the database without adding `$TORK_OUTPUT`) And thanks a lot that you are fixing all bugs really fast. Now there are some `feature request` created from my side but they are about `tork-web` - you have to improve the `face` of your app :)

I have a similar usecase. Can you please share your `tork-docker` Dockerfile and charts?

**Comment by v36372** [comment]
@runabol I'm trying out parallel tasks and was just wondering how to limit the number of worker containers? Maybe my input list is too big and I don't want 1000 containers to be spawned, just 10 containers to process the list in a FIFO manner?

**Comment by ppcololo** [comment]
> @runabol I'm trying out parallel tasks and was just wondering how to limit the number of worker containers? Maybe my input list is too big and I don't want 1000 containers to be spawned, just 10 containers to process the list in a FIFO manner?

You can check in here: https://github.com/runabol/tork/issues/172#issuecomment-1722550001

@runabol you have to add this info into `sample.config`

**Comment by v36372** [comment]
@ppcololo When you run tork on k8s, how did you handle autoscaling of pods for worker?

**Comment by ppcololo** [comment]
for now - only manual configuration.
need to think how to Autoscale them: maybe implement some HPA - depending on tasks count, dunno right now

**Comment by v36372** [comment]
For worker deployment. I'm mounting the host (pod) docker unix socket into the worker container. Is there a better way to deploy worker on cloud? Ideally, a k8s runtime implementation is better suited because we can create new pod for the job container on demand. Instead of having to run the job container on the worker pod. Thoughts? @ppcololo @runabol

**Comment by ppcololo** [comment]
@v36372 my dockerfile
```
FROM alpine:3.16
RUN apk update && apk add git wget tar gettext python3 py3-pip
ADD https://github.com/runabol/tork/releases/download/v0.1.19/default.release.tork_0.1.19_linux_amd64.tgz tork.tgz
RUN tar -zxf tork.tgz
COPY config.toml .
RUN chmod +x tork
ENTRYPOINT ./tork run worker
```
and config:
```
[broker]
type = "rabbitmq"

[broker.rabbitmq]
url = "RABBIT_URL"
consumer.timeout = "600m"

[worker.queues]
default = 1

[runtime]
type = "shell"

[runtime.shell]
cmd = ["/bin/sh", "-c"]
```
so you can build your image and push to dockerhub
prepare simple k8s deployment and deploy tork-worker there with `replicas: 1`
Then you can scale it via cli: 
`kubectl scale deployment tork --replicas=X`
