### ISSUE TITLE
Issue with rabbitmq and long tasks

### ISSUE THREAD

**Issue by ppcololo** [runabol/tork#208]
Hello.
I faced with strange issue: I have a lot of long tasks > 5 hours. And after task finished I see errors in the logs:

```
tork[3136]: 9:52PM ERR failed to ack message error="Exception (504) Reason: \"channel/connection is not open\""
```
Also I see this inside rabbitmq settings:
![image](https://github.com/runabol/tork/assets/35843703/fcf06876-66c6-4d47-90ea-88ed5c4311f9)

Maybe it relates to each other but after tork-worker finishes task it receives this error ans start this task again...:

```
Oct 02 16:44:21 ruvds-tiy9w tork[81156]: 4:44PM DBG received task task-id=639c83e4a371467c8add77f3031806f8
Oct 02 16:44:21 ruvds-tiy9w tork[81156]: 4:44PM DBG Created workdir /tmp/tork3494944280
Oct 02 16:44:22 ruvds-tiy9w tork[81156]: 4:44PM INF Config loaded from /etc/tork/config.toml
Oct 02 16:44:22 ruvds-tiy9w tork[81156]: {"level":"debug","time":"2023-10-02T16:44:22+03:00","message":"reexecing: bash -c /tmp/tork3494944280/entrypoint as -:-"}
Oct 02 16:44:22 ruvds-tiy9w tork[81156]: Start at 2023-10-02 13:44:22.635340645 +0000 UTC
.......
Oct 02 20:13:32 ruvds-tiy9w tork[81156]: FINISHED --2023-10-02 20:13:32--
Oct 02 20:13:32 ruvds-tiy9w tork[81156]: Total wall clock time: 3h 29m 9s
```

and same task again:
```
Oct 02 20:13:33 ruvds-tiy9w tork[81156]: 8:13PM ERR failed to ack message error="Exception (504) Reason: \"channel/connection is not open\""
Oct 02 20:13:33 ruvds-tiy9w tork[81156]: 8:13PM INF default channel closed. reconnecting
Oct 02 20:13:33 ruvds-tiy9w tork[81156]: 8:13PM DBG created channel de321733e2b74c368ad0d3cf33c7e78f for queue: default
Oct 02 20:13:33 ruvds-tiy9w tork[81156]: 8:13PM DBG received task task-id=639c83e4a371467c8add77f3031806f8
Oct 02 20:13:33 ruvds-tiy9w tork[81156]: 8:13PM DBG Created workdir /tmp/tork4048566087
Oct 02 20:13:33 ruvds-tiy9w tork[81156]: 8:13PM INF Config loaded from /etc/tork/config.toml
Oct 02 20:13:33 ruvds-tiy9w tork[81156]: {"level":"debug","time":"2023-10-02T20:13:33+03:00","message":"reexecing: bash -c /tmp/tork4048566087/entrypoint as -:-"}
Oct 02 20:13:34 ruvds-tiy9w tork[81156]: Start at 2023-10-02 17:13:34.102253289 +0000 UTC
```
So as you can see it receives the same task again:
```
task task-id=639c83e4a371467c8add77f3031806f8
```

Logs inside rabbitmq:
```
2023-10-03 19:23:01.214304+00:00 [error] <0.13814.7> Channel error on connection <0.1216.0> (ip:51850 -> ip2.3:5672, vhost: '/', user: 'rabbit'), channel 13:
2023-10-03 19:23:01.214304+00:00 [error] <0.13814.7> operation none caused a channel exception precondition_failed: delivery acknowledgement on channel 13 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more
```

Maybe `tork-worker` can send some `keep-alive` to rabbitmq?

**Comment by runabol** [comment]
Interesting. Yes, that does smell like a timeout. Seems like the original connection that delivered the message closes by the time the task finishes. I'll take a look.

**Comment by runabol** [comment]
@ppcololo please see https://github.com/runabol/tork/pull/209 

Using the new config property `broker.rabbitmq.consumer.timeout` should resolve your issue.

**Comment by ppcololo** [comment]
thanks a lot! checked - `timeout` has correct value in `rabbitmq` now

**Comment by ppcololo** [comment]
Sorry, have to reopen this issue:
seems workers after finish first task - taking another task without sending this `timeout` or there something different:
so, I faced with strange situation: 
- I've updated workers to 0.1.19
- I've created 150 parallel tasks
- when workers took the first tasks I saw correct timeout
- but after some time when first workers finished their tasks I saw the same error:
`ERR failed to ack message error="Exception (504) Reason: \"channel/connection is not open\""` but task was finished
- but some workers took not `Scheduled` task but they took `Running` task and now I can see that one task executed on two workers... Ofcourse not in UI but in workers logs.

Could it be because I didn't update coordinator to the latest version? I've updated only workers to solve this issue with rabbitmq timeout

**Comment by runabol** [comment]
I should have mentioned that you'd want to shutdown and start RabbitMQ again from scratch with no queues.

The timeout is configured on the queue at the creation of the queue. And you'd probably want to also update the coordinator in case it creates a queue when it sends the first message.

See if this solves the issue.

**Comment by ppcololo** [comment]
ok, thanks, I will try
I had to update coordinator ofcouse, but I forgot to do this
