### ISSUE TITLE
[feature request] If one parallel task fails - don't fail entire Job

### ISSUE THREAD

**Issue by ppcololo** [runabol/tork#210]
Hello
Really important feature:
If one parallel task fails - don't fail entire Job and add possibility to re-run failed Task

Our case:
we have one big Job with 50x parallel tasks inside. Task lifetime > 5h. And If one task fails - it fails entire Job and we lose results of another workers.
If we restart this Job different workers can pickup random tasks again and it will the mess for us.

And one question: if task fails - will the `post` work after this?

**Comment by runabol** [comment]
You can add a `retry` property to the parallel task you want  to retry in case of failure. Example:

https://github.com/runabol/tork/blob/14b275c8e79c2c03dc8dd5385951adca689c9190/examples/hls.yaml#L58

Post tasks do not execute if the task fails.

**Comment by ppcololo** [comment]
But is it possible to fail one of parallel tasks? And not entire Job?
What if one task fill fail forever?

**Comment by runabol** [comment]
It would be inconsistent to not fail the parallel task if one of its tasks fail.
