### ISSUE TITLE
[feature request] Export host PATH for tasks

### ISSUE THREAD

**Issue by ppcololo** [runabol/tork#217]
Hello.
Faced with issue when `tork-worker` inside task can't find some commands. For now I have to set whole PATH for some commands.
Is it possible to pass host PATH to `tork-worker` tasks?

**Comment by runabol** [comment]
That should already be the case: https://github.com/runabol/tork/blob/3fbc4bc26388d6e5b3baaff2fa95a04862a75aac/runtime/shell/shell.go#L144

**Comment by ppcololo** [comment]
Ok, thanks. Maybe my fault, will check
