### ISSUE TITLE
Load some config values from env and merge with config.toml

### ISSUE THREAD

**Issue by v36372** [runabol/tork#218]
I'm using both `config.toml` and some secrets to be injected as envs.

I notice that `conf` package loads from the first found config file and then exit, leaving the envs loading untouched.
```go
	// load configs from file paths
	for _, f := range paths {
		err := konf.Load(file.Provider(f), toml.Parser())
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return errors.Wrapf(err, "error loading config from %s", f)
		}
		logger.Info().Msgf("Config loaded from %s", f)
		return nil
	}
	// load configs from env vars
	if err := konf.Load(env.Provider("TORK_", ".", func(s string) string {
		return strings.Replace(strings.ToLower(
			strings.TrimPrefix(s, "TORK_")), "_", ".", -1)
	}), nil); err != nil {
		return errors.Wrapf(err, "error loading config from env")
	}
```

Ideally, what I want is to be able to load some config values from env and override that value in the `config.toml`. Something like this:
```go
         // load configs from file paths
	for _, f := range paths {
                 ...
		break
	}
	// load configs from env vars
        ...
```

Not sure if it's the correct approach to get what I want so I didn't create a PR.

**Comment by runabol** [comment]
This is poorly documented, so I'll fix that. But you can override any property using an environment variable using: `TORK_CONFIG_PROPERTY` replacing dots with underscores. Example `TORK_LOGGING_LEVEL=warn`

**Comment by v36372** [comment]
I know we can override configs doing that. But I doubt working atm. I have the following envs loaded in docker-compose:

<img width="965" alt="Screenshot 2023-10-16 at 11 37 06" src="https://github.com/runabol/tork/assets/7565018/b4fffb1e-1628-403d-907b-adbb9d1b5695">

And the coordinator keeps having error:

```bash
2023-10-16 11:58:09 4:58AM INF Config loaded from /etc/tork/config.toml
2023-10-16 11:58:09 panic: unable to connect to RabbitMQ: error dialing to RabbitMQ: dial tcp 127.0.0.1:5672: connect: connection refused
```

**Comment by runabol** [comment]
You are correct. There was an issue when mixing config file and env var. This should fix that: https://github.com/runabol/tork/pull/221
