### ISSUE TITLE
Add task timeout

### ISSUE THREAD

**Issue by ppcololo** [runabol/tork#223]
From time to time some workers hang due to execution script.

Example:
we have python scripts + playwright Firefox browser. Sometimes this Firefox hangs and task stops. In this state it could be long time before we identify that this is fail of script (and another worker already finish this task due to Queue timeout).

So we know average time of task execution and is it possible to add some value during Job creation that if task executing longer than X we can restart it?

**Comment by ppcololo** [comment]
What are the possible values?
timeout: 10s|10m|10h|10d?

**Comment by runabol** [comment]
Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h", "d", "w", "y".

**Comment by ppcololo** [comment]
Thanks a lot!
