### ISSUE TITLE
priority of a job

### ISSUE THREAD

**Issue by dreamCodeMan** [runabol/tork#251]
You can use RabbitMQ's priority to determine the priority of a job, thereby ensuring the order of jobs.

**Comment by ppcololo** [comment]
Really useful feature: 
we have a really big queue of parallel tasks in the many jobs.
But if some urgent task appears - we can't move it to the beggining of the queue - it could be placed only to the end. In this case we have to create a new worker with some new queue name and place this taks in this new queue.

**Comment by runabol** [comment]
Yeah I'll bump this issue in priority 🙂. Shouldn't be too hard to implement.

**Comment by runabol** [comment]
Thoughts? https://github.com/runabol/tork/pull/392

**Comment by gaby** [comment]
@runabol That's awesome

**Comment by dreamCodeMan** [comment]
@runabol That's awesome!
