### ISSUE TITLE
[feature] Tork worker default folder

### ISSUE THREAD

**Issue by ppcololo** [runabol/tork#263]
Hello
Now all shell workers create directoty under `/tmp` and it looks like `/tmp/tork[SOME_ID]`
Is it possible to change default directory to:
`/tmp/[CONFIGURABLE_PATH]/tork[SOME_ID]`?

somethin like this:
`workdir, err := os.MkdirTemp(worker_path, "tork")`

**Comment by runabol** [comment]
Did you try changing the temporary directory location using Go's [TMPDIR](https://github.com/golang/go/blob/d6ef98b8fa4851f025779ef4ade084d63290de2a/src/os/file_unix.go#L392) env var since Tork relies on the standard library to generate temporary dirs?

**Comment by ppcololo** [comment]
Will test this, thanks
