### ISSUE TITLE
feature request: Download all logs for a job

### ISSUE THREAD

**Issue by v36372** [runabol/tork#311]
Hi, I am having a need to download all logs belong to a jobs. Something like the SQL query below
```SQL
SELECT
	contents
FROM
	tasks_log_parts
WHERE
	task_id in(
		SELECT
			id FROM tasks
		WHERE
			job_id = 'b9cffbdc0a24451fa09763e80eb6b4ce')
ORDER BY
	number_;
```

Also, may I ask why does some log lines got prepended by some random bytes like this:
<img width="518" alt="Screenshot 2024-01-10 at 18 05 35" src="https://github.com/runabol/tork/assets/7565018/23b09ab5-1e84-4b48-9ec5-2c148e1b53a8">

**Comment by bit-wiz** [comment]
> Hi, I am having a need to download all logs belong to a jobs. Something like the SQL query below
> 
> ```sql
> SELECT
> 	contents
> FROM
> 	tasks_log_parts
> WHERE
> 	task_id in(
> 		SELECT
> 			id FROM tasks
> 		WHERE
> 			job_id = 'b9cffbdc0a24451fa09763e80eb6b4ce')
> ORDER BY
> 	number_;
> ```
> 
> Also, may I ask why does some log lines got prepended by some random bytes like this: <img alt="Screenshot 2024-01-10 at 18 05 35" width="518" src="https://private-user-images.githubusercontent.com/7565018/295544152-23b09ab5-1e84-4b48-9ec5-2c148e1b53a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTE5MjAsIm5iZiI6MTcwNDg5MTYyMCwicGF0aCI6Ii83NTY1MDE4LzI5NTU0NDE1Mi0yM2IwOWFiNS0xZTg0LTRiNDgtOWVjNS0yYzE0OGUxYjUzYTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMTMwMDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNkZGY2ZWNlNjZlZDhhMGEwM2Q0NzhjYzUyNWJiZjgwNmY3OGI1NGJiZDhmYmE1ZWQ1N2YwYWNhMmZjZDUwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UQdIFGgAVfyk-q9pw5mNsmEGcNL1LqUv30vQYgCfUGc">

You need to download the logs in .txt right ? so could just add download button in frontend.  or am I missing something here ?

**Comment by runabol** [comment]
@v36372 concerning the strange prefixes in the logs, the latest release should fix that. 

As for getting all the task logs for a single job you could call the `/tasks/:id/log` endpoint for each task in your job using the APIs.

**Comment by bit-wiz** [comment]
@runabol I have added download btn which will download a .txt file of all the logs in frontend next js code ( in logs and view both )

![photo_2024-01-10_20-00-41](https://github.com/runabol/tork/assets/137268493/2aef9b9b-7a3e-4e00-99f6-b187b0869669)

**Comment by v36372** [comment]
Thanks @runabol. 

Another related observation is that the logs are reversed in order when returned from the API. I personally think it would be more intuitive if it was newest logs at the bottom and the Frontend NextJS would auto scroll to bottom when refreshed.

@bit-wiz Thank you for the download button. But did you create a PR in https://github.com/runabol/tork-web?

**Comment by bit-wiz** [comment]
> Thanks @runabol.
> 
> Another related observation is that the logs are reversed in order when returned from the API. I personally think it would be more intuitive if it was newest logs at the bottom and the Frontend NextJS would auto scroll to bottom when refreshed.
> 
> @bit-wiz Thank you for the download button. But did you create a PR in https://github.com/runabol/tork-web?

yeah just did, I was waiting for confirmation

**Comment by runabol** [comment]
> Another related observation is that the logs are reversed in order when returned from the API. I personally think it would be more intuitive if it was newest logs at the bottom and the Frontend NextJS would auto scroll to bottom when refreshed.

Task logs can get quite large (MBs is not uncommon in our use cases) and would tax both the backend and the UI unnecessarily. I think it's better to fetch the last page of the log and retrieve additional pages one by one as needed.
