### ISSUE TITLE
Like how simple this application is. How to contribute? 

### ISSUE THREAD

**Issue by mingsterism** [runabol/tork#338]
i love how simple this library is. is there any way to see a roadmap of what needs to be done? From there it would be easier to contribute as well. 

Cheers

**Comment by mingsterism** [comment]
thanks. i think my thoughts regarding a roadmap is really to also understand the future of this project? or where would it be heading? perhaps your vision for this? i see that you took the trouble to recreate this in golang from your previous project so was curious if you had a bigger goal.

**Comment by runabol** [comment]
For me it's about seeing people use it. There's no commercial incentive here. I rewrote it because I like Go and I wanted to address the shortcomings of the previous iteration.

**Comment by runabol** [comment]
Parsing the value has too many edge cases. Example:

`{{inputs.not_a_secret}}/actual_secret`

So if I don't redact this it will have the secret in the clear. 

That's why I'm thinking of adding a new `secrets` construct that will be more explicit.
