### ISSUE TITLE
Kicking jobs off with arbitrary data

### ISSUE THREAD

**Issue by jspc** [runabol/tork#363]
Is there any way to set arbitrary data/ job context when `POST`ing a job yaml to tork?

Right now the flow I have is:

```mermaid
sequenceDiagram
    Dispatcher->>Tork: Create job
    Tork->>Dispatcher: JobSummary
    Dispatcher->>Dispatcher: Create config, persist job ID
    opt On Job Start
    Tork->>Dispatcher: Get Job Config
    Dispatcher->>Tork: map[string]string
    end
```

But what I'd quite like is to be able to kick a job off _with_ some additional data.

If it can't be done, are there any other ways you can think of that would do this? I know tasks can have tags, which I could potentially mis-use

**Comment by runabol** [comment]
Yea, see job inputs: https://www.tork.run/jobs

**Comment by jspc** [comment]
Ah, gotcha. My current workflow, as it were, is that the dispatcher posts yaml from disk- I guess what I need to do is parse that yaml, add inputs, then `POST`.

Which isn't an issue
