### ISSUE TITLE
Setting job failed state in Job HandlerFunc

### ISSUE THREAD

**Issue by jspc** [runabol/tork#366]
Consider the `job.HandlerFunc`

```golang
func erroringHandlerFunc(next job.HandlerFunc) job.HandlerFunc {
	return func(ctx context.Context, et job.EventType, j *tork.Job) (err error) {
		if et == job.Read {
			return next(ctx, et, j)
		}

                return errors.New("some error")
       }
}
```

When this gets called the logs, as expected, show `ERR unexpcted error occurred while processing task error="some error"`, however the status of the Job remains as `PENDING`, where I'd expect it to be `FAILED`.

I've tried to manually update the job to set the expected state, but this seems to be ignored.

Is this a bug, or am I doing something wrong?

**Comment by runabol** [comment]
I see your point. Generally, middleware is not meant to disrupt the flow of the job/task but only intercept it. An error in a middleware is considered an error in the middleware itself -- not with the job/task itself.

**Comment by runabol** [comment]
But that being said, you write a task middleware that sends the the task to the m `error` queue to fail the job.

**Comment by runabol** [comment]
@jspc thoughts? https://github.com/runabol/tork/pull/424
