### ISSUE TITLE
Suggestion: Expose Connector Interfaces for Databases and Queues

### ISSUE THREAD

**Issue by mrchypark** [runabol/tork#440]
Hi Tork team! 👋

First off, I want to say that I really appreciate the work you're doing on this project. It's great to see support for in-memory and PostgreSQL databases, as well as in-memory and RabbitMQ queues.

## Current Situation
Currently, Tork supports:
- Databases: in-memory and PostgreSQL
- Queues: in-memory and RabbitMQ

## Suggestion
I think it would be beneficial to expose the connector interfaces for both databases and queues. This could pave the way for easier integration of additional connectors in the future.

## Benefits
By exposing these interfaces, we could:
1. Make it easier for the community to contribute new connectors (e.g., SQLite for databases or SQS for queues)
2. Increase the flexibility of the project, allowing users to implement connectors for their specific needs
3. Potentially broaden the use cases for Tork without significantly increasing the core maintenance burden

## Potential Implementation
This could involve creating abstract interfaces for database and queue connectors, which the current implementations would then implement. New connectors could simply implement these interfaces to be compatible with Tork.

## Questions
- What are your thoughts on this approach?
- Are there any potential drawbacks or challenges you foresee?
- Would you be open to a PR that implements this change?

Thank you for considering this suggestion. I'm excited to see how Tork continues to evolve!

**Comment by runabol** [comment]
Hi @mrchypark. Thank you for the kind words and for your suggestions. 

Tork actually does already expose the [Datastore](https://github.com/runabol/tork/blob/main/datastore/datastore.go#L26) and [Broker](https://github.com/runabol/tork/blob/main/mq/broker.go#L20) as interfaces. 

Furthermore, it's quite easy to register new ones when extending Tork.
See: https://www.tork.run/datastore and https://www.tork.run/broker

Does this handle these use cases?

**Comment by mrchypark** [comment]
Here's a friendly English translation of the given Korean text:
Oh, it was really well done! I feel a bit embarrassed for having written the issue. I've confirmed that both are working perfectly. Thank you so much for letting me know. In my case, I needed to add SQLite and SQS, which I think I'll be able to do now.
Thank you once again for your guidance. I really appreciate it.
