### ISSUE TITLE
Question: is there a way to run locally build images?

### ISSUE THREAD

**Issue by arturo32** [runabol/tork#451]
My use case is that I want to make a  Go API that compiles C/C++ code and run it with gdb. So I just need a very simple image that have gcc and gdb, for example.

**Comment by runabol** [comment]
@arturo32 Yea, so long as the image is available for the worker that received the task locally then it will not attempt to pull it from a remote repo. The Docker runtime, first [checks if the image exists locally](https://github.com/runabol/tork/blob/455cdfdb43491c3c385adbdca7e473640f9a8ad2/runtime/docker/docker.go#L708) before trying to pull it.

**Comment by arturo32** [comment]
> @arturo32 Yea, so long as the image is available for the worker that received the task locally, then it will not attempt to pull it from a remote repo. The Docker runtime, first [checks if the image exists locally](https://github.com/runabol/tork/blob/455cdfdb43491c3c385adbdca7e473640f9a8ad2/runtime/docker/docker.go#L708) before trying to pull it.

Omg, thank you very much! I'm not very well versed in docker and I'm using your tool for my graduation thesis (an educational website for learning how pointers in programming work).

**Comment by runabol** [comment]
That's very cool. Let me know if you have any other questions. And good luck with your thesis!
