### ISSUE TITLE
Tork running on AWS EC2, cannot access port 8000

### ISSUE THREAD

**Issue by Khacke** [runabol/tork#453]
Hello! I'm building a code execution project and using Tork for the execution component. I had no issues running Tork locally. However, after migrating it to an AWS EC2 instance, I’m unable to access Tork from another machine.

Here's what I've set up:
- I configured a security group to expose port 8000.
- When I run a Python HTTP server on port 8000, it works perfectly.

The issue arises with Tork:
- When Tork is running on port 8000, I can’t access GET /health or POST /jobs to create new jobs from another machine.

Do you have any idea why this might be happening? If this issue isn’t related to Tork itself, feel free to close it.

**Comment by runabol** [comment]
By default the Tork Coordinator listens on the `localhost` interface which might not work on EC2. Can you try allowing it to listen on all interfaces. e.g.: 

```
TORK_COORDINATOR_ADDRESS="0.0.0.0:8000"
```
