### ISSUE TITLE
Allow posting a job through JSON

### ISSUE THREAD

**Issue by mingsterism** [runabol/tork#455]
Are we able to allow JSON instead of YAML format when passing a job to tork 

I noticed in the documentation it only allows for YAML
![image](https://github.com/user-attachments/assets/c744e4cd-64e4-4807-8e40-90781a784afe)
To allow for passing JSON do we just extend that API to allow for it? 
What's the best way to do this?

**Comment by runabol** [comment]
Not documented, but is doable:

```bash
curl -s -X POST -H "content-type:application/json" -d '{
  "name": "hello job", 
  "tasks": [{
     "name": "say hello", 
      "image": "ubuntu:mantic", 
      "run": "echo -n hello world\n" 
  }]
}' http://localhost:8000/jobs | jq .
```
